// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/repository (interfaces: IPaymentsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockIPaymentsRepository is a mock of IPaymentsRepository interface.
type MockIPaymentsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentsRepositoryMockRecorder
}

// MockIPaymentsRepositoryMockRecorder is the mock recorder for MockIPaymentsRepository.
type MockIPaymentsRepositoryMockRecorder struct {
	mock *MockIPaymentsRepository
}

// NewMockIPaymentsRepository creates a new mock instance.
func NewMockIPaymentsRepository(ctrl *gomock.Controller) *MockIPaymentsRepository {
	mock := &MockIPaymentsRepository{ctrl: ctrl}
	mock.recorder = &MockIPaymentsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentsRepository) EXPECT() *MockIPaymentsRepositoryMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockIPaymentsRepository) AddPayment(arg0 repository.Payment) (*repository.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPayment", arg0)
	ret0, _ := ret[0].(*repository.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockIPaymentsRepositoryMockRecorder) AddPayment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockIPaymentsRepository)(nil).AddPayment), arg0)
}

// GetPayment mocks base method.
func (m *MockIPaymentsRepository) GetPayment(arg0 string) *repository.Payment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", arg0)
	ret0, _ := ret[0].(*repository.Payment)
	return ret0
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockIPaymentsRepositoryMockRecorder) GetPayment(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockIPaymentsRepository)(nil).GetPayment), arg0)
}
