// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/http/clients (interfaces: IBankSimAPI)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/http/clients/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIBankSimAPI is a mock of IBankSimAPI interface.
type MockIBankSimAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIBankSimAPIMockRecorder
}

// MockIBankSimAPIMockRecorder is the mock recorder for MockIBankSimAPI.
type MockIBankSimAPIMockRecorder struct {
	mock *MockIBankSimAPI
}

// NewMockIBankSimAPI creates a new mock instance.
func NewMockIBankSimAPI(ctrl *gomock.Controller) *MockIBankSimAPI {
	mock := &MockIBankSimAPI{ctrl: ctrl}
	mock.recorder = &MockIBankSimAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBankSimAPI) EXPECT() *MockIBankSimAPIMockRecorder {
	return m.recorder
}

// ForwardPaymentRequest mocks base method.
func (m *MockIBankSimAPI) ForwardPaymentRequest(arg0 string, arg1 *models.BankSimPaymentRequest) (*models.BankSimPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForwardPaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(*models.BankSimPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForwardPaymentRequest indicates an expected call of ForwardPaymentRequest.
func (mr *MockIBankSimAPIMockRecorder) ForwardPaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardPaymentRequest", reflect.TypeOf((*MockIBankSimAPI)(nil).ForwardPaymentRequest), arg0, arg1)
}
