// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/http/clients (interfaces: IBankSimApiRetryHandler)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/ports/http/clients/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIBankSimApiRetryHandler is a mock of IBankSimApiRetryHandler interface.
type MockIBankSimApiRetryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIBankSimApiRetryHandlerMockRecorder
}

// MockIBankSimApiRetryHandlerMockRecorder is the mock recorder for MockIBankSimApiRetryHandler.
type MockIBankSimApiRetryHandlerMockRecorder struct {
	mock *MockIBankSimApiRetryHandler
}

// NewMockIBankSimApiRetryHandler creates a new mock instance.
func NewMockIBankSimApiRetryHandler(ctrl *gomock.Controller) *MockIBankSimApiRetryHandler {
	mock := &MockIBankSimApiRetryHandler{ctrl: ctrl}
	mock.recorder = &MockIBankSimApiRetryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBankSimApiRetryHandler) EXPECT() *MockIBankSimApiRetryHandlerMockRecorder {
	return m.recorder
}

// BeginRetry mocks base method.
func (m *MockIBankSimApiRetryHandler) BeginRetry(arg0, arg1 string, arg2 *models.BankSimPaymentRequest) (*models.BankSimPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginRetry", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.BankSimPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginRetry indicates an expected call of BeginRetry.
func (mr *MockIBankSimApiRetryHandlerMockRecorder) BeginRetry(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginRetry", reflect.TypeOf((*MockIBankSimApiRetryHandler)(nil).BeginRetry), arg0, arg1, arg2)
}
