// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/pkg/helpers (interfaces: IPaymentIDCreator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPaymentIDCreator is a mock of IPaymentIDCreator interface.
type MockIPaymentIDCreator struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentIDCreatorMockRecorder
}

// MockIPaymentIDCreatorMockRecorder is the mock recorder for MockIPaymentIDCreator.
type MockIPaymentIDCreatorMockRecorder struct {
	mock *MockIPaymentIDCreator
}

// NewMockIPaymentIDCreator creates a new mock instance.
func NewMockIPaymentIDCreator(ctrl *gomock.Controller) *MockIPaymentIDCreator {
	mock := &MockIPaymentIDCreator{ctrl: ctrl}
	mock.recorder = &MockIPaymentIDCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentIDCreator) EXPECT() *MockIPaymentIDCreatorMockRecorder {
	return m.recorder
}

// CreatePaymentID mocks base method.
func (m *MockIPaymentIDCreator) CreatePaymentID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentID")
	ret0, _ := ret[0].(string)
	return ret0
}

// CreatePaymentID indicates an expected call of CreatePaymentID.
func (mr *MockIPaymentIDCreatorMockRecorder) CreatePaymentID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentID", reflect.TypeOf((*MockIPaymentIDCreator)(nil).CreatePaymentID))
}
