// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cko-recruitment/payment-gateway-challenge-go/internal/pkg/validation (interfaces: IPaymentValidator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/cko-recruitment/payment-gateway-challenge-go/internal/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIPaymentValidator is a mock of IPaymentValidator interface.
type MockIPaymentValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIPaymentValidatorMockRecorder
}

// MockIPaymentValidatorMockRecorder is the mock recorder for MockIPaymentValidator.
type MockIPaymentValidatorMockRecorder struct {
	mock *MockIPaymentValidator
}

// NewMockIPaymentValidator creates a new mock instance.
func NewMockIPaymentValidator(ctrl *gomock.Controller) *MockIPaymentValidator {
	mock := &MockIPaymentValidator{ctrl: ctrl}
	mock.recorder = &MockIPaymentValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPaymentValidator) EXPECT() *MockIPaymentValidatorMockRecorder {
	return m.recorder
}

// ValidateProcessPaymentRequest mocks base method.
func (m *MockIPaymentValidator) ValidateProcessPaymentRequest(arg0 string, arg1 *models.ProcessPaymentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateProcessPaymentRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateProcessPaymentRequest indicates an expected call of ValidateProcessPaymentRequest.
func (mr *MockIPaymentValidatorMockRecorder) ValidateProcessPaymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateProcessPaymentRequest", reflect.TypeOf((*MockIPaymentValidator)(nil).ValidateProcessPaymentRequest), arg0, arg1)
}
